name-template: 'v$NEXT_MINOR_VERSION'
tag-template: 'v$NEXT_MINOR_VERSION'
categories:
  - title: 'ğŸš€ Features'
    label: 'enhancement'
  - title: 'ğŸ› bugfix'
    label: 'bugfix'
  - title: 'ğŸª¡refactoring'
    label: 'refactoring'
change-template: '- $TITLE #$NUMBER @$AUTHOR '
template: |
  $CHANGES
